name: test_pragma
description: "FlutterTest Pragma Mobile."


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  #Route
  go_router: ^14.2.8
  #DI
  get_it: ^8.0.0
  #Image Svg
  flutter_svg: ^2.0.15
  #State
  provider: ^6.1.2
  #Apis
  dio: ^5.7.0
  http: ^1.2.2
  #Image Cache
  cached_network_image: ^3.4.1
  #link
  easy_url_launcher: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf 

    - family: LTCushion
      fonts:
        - asset: assets/fonts/LTCushion-Bold.ttf  

    - family: InterphasesBold
      fonts:
        - asset: assets/fonts/InterphasesBold.ttf       

    - family: RugenExpanded
      fonts:
        - asset: assets/fonts/RugenExpanded.ttf         

    - family: RugenExpanded
      fonts:
        - asset: assets/fonts/Blue.ttf   

    - family: BREECBO
      fonts:
        - asset: assets/fonts/BREECBO.ttf   

    - family: Digital
      fonts:
        - asset: assets/fonts/Digital.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf  
   

  